### ISSUE TITLE
Need more functionality 

### ISSUE THREAD

**Issue by suman-shah** [Parbej275/Area-of-rectangle-#1]
**### Can you please add more features to this program like adding new features to calculate area of rectangular of any object by asking user to give input and then calculating area.**

**Comment by Parbej275** [comment]
This is informed to you Mr. suman shah to work in this issue it will be highly apricated

**Comment by suman-shah** [comment]
i am working on it sir . 😎

**Comment by Parbej275** [comment]
Thanks for solving the issue, it is appreciated from bottom of my heart.
